// 장비 옵션 풀 (재화 = 옵션 변경 재봉틀). 구조 설명은 optionData.js 참고.
// 모든 장비는 줄별 풀(linePools): 각 줄이 자기 줄 풀에서 독립 추첨(중복 허용). 1·2줄 동일, 3줄 중간값, 4줄 최대값.

export const equipSlots = {
    shoes: {
        group: 'equip',
        lines: 4,
        lockCost: { 0: 1, 1: 2, 2: 5 },
        items: [
            {
                name: '스피릿의 신발',
                linePools: [
                    [
                        { name: '공격력',          min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',          min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',        min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',        min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',        min: 35,  max: 150,  dp: 0 },
                        { name: '회피',            min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',            min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',       min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 1,   max: 3,    dp: 2 },
                        { name: '치명피해(%)',      min: 5,   max: 8.5,  dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',          min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',        min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',        min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',        min: 35,  max: 150,  dp: 0 },
                        { name: '회피',            min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',            min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',       min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 1,   max: 3,    dp: 2 },
                        { name: '치명피해(%)',      min: 5,   max: 8.5,  dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 150,  dp: 0 },
                        { name: '방어력',          min: 50,  max: 300,  dp: 0 },
                        { name: '최대체력',        min: 150, max: 600,  dp: 0 },
                        { name: '디지소울',        min: 150, max: 600,  dp: 0 },
                        { name: '스킬피해',        min: 50,  max: 300,  dp: 0 },
                        { name: '회피',            min: 2,   max: 4,    dp: 0 },
                        { name: '블럭',            min: 2,   max: 4,    dp: 0 },
                        { name: '방어력(%)',       min: 2,   max: 5,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 2,   max: 5,    dp: 2 },
                        { name: '크리티컬',        min: 1,   max: 3,    dp: 2 },
                        { name: '적중도',          min: 200, max: 400,  dp: 2 },
                        { name: '치명피해(%)',      min: 3.75, max: 11.5, dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 300,  dp: 0 },
                        { name: '방어력',          min: 50,  max: 600,  dp: 0 },
                        { name: '최대체력',        min: 150, max: 1200, dp: 0 },
                        { name: '디지소울',        min: 150, max: 1200, dp: 0 },
                        { name: '스킬피해',        min: 50,  max: 600,  dp: 0 },
                        { name: '회피',            min: 2,   max: 8,    dp: 0 },
                        { name: '블럭',            min: 2,   max: 8,    dp: 0 },
                        { name: '방어력(%)',       min: 2,   max: 10,   dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 2,   max: 10,   dp: 2 },
                        { name: '크리티컬',        min: 2,   max: 5,    dp: 2 },
                        { name: '적중도',          min: 250, max: 600,  dp: 2 },
                        { name: '치명피해(%)',      min: 1.25, max: 16.5, dp: 2 },
                    ],
                ],
            },
        ],
    },

    top: {
        group: 'equip',
        lines: 4,
        lockCost: { 0: 1, 1: 2, 2: 5 },
        items: [
            {
                name: '스피릿의 상의',
                linePools: [
                    [
                        { name: '공격력',          min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',          min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',        min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',        min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',        min: 35,  max: 150,  dp: 0 },
                        { name: '회피',            min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',            min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',       min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 1,   max: 3,    dp: 2 },
                        { name: '최대 HP 증가(%)',  min: 0.7,  max: 0.85, dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',          min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',        min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',        min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',        min: 35,  max: 150,  dp: 0 },
                        { name: '회피',            min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',            min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',       min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 1,   max: 3,    dp: 2 },
                        { name: '최대 HP 증가(%)',  min: 0.7,  max: 0.85, dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 150,  dp: 0 },
                        { name: '방어력',          min: 50,  max: 300,  dp: 0 },
                        { name: '최대체력',        min: 150, max: 600,  dp: 0 },
                        { name: '디지소울',        min: 150, max: 600,  dp: 0 },
                        { name: '스킬피해',        min: 50,  max: 300,  dp: 0 },
                        { name: '회피',            min: 2,   max: 4,    dp: 0 },
                        { name: '블럭',            min: 2,   max: 4,    dp: 0 },
                        { name: '방어력(%)',       min: 2,   max: 5,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 2,   max: 5,    dp: 2 },
                        { name: '크리티컬',        min: 1,   max: 3,    dp: 2 },
                        { name: '적중도',          min: 200, max: 400,  dp: 2 },
                        { name: '최대 HP 증가(%)',  min: 0.45, max: 1.3,  dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 300,  dp: 0 },
                        { name: '방어력',          min: 50,  max: 600,  dp: 0 },
                        { name: '최대체력',        min: 150, max: 1200, dp: 0 },
                        { name: '디지소울',        min: 150, max: 1200, dp: 0 },
                        { name: '스킬피해',        min: 50,  max: 600,  dp: 0 },
                        { name: '회피',            min: 2,   max: 8,    dp: 0 },
                        { name: '블럭',            min: 2,   max: 8,    dp: 0 },
                        { name: '방어력(%)',       min: 2,   max: 10,   dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 2,   max: 10,   dp: 2 },
                        { name: '크리티컬',        min: 2,   max: 5,    dp: 2 },
                        { name: '적중도',          min: 250, max: 600,  dp: 2 },
                        { name: '최대 HP 증가(%)',  min: 0.15, max: 2.0,  dp: 2 },
                    ],
                ],
            },
        ],
    },

    emblem: {
        group: 'equip',
        lines: 4,
        lockCost: { 0: 1, 1: 2, 2: 5 },
        items: [
            {
                name: '스피릿의 모자',
                linePools: [
                    [
                        { name: '공격력',          min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',          min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',        min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',        min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',        min: 35,  max: 150,  dp: 0 },
                        { name: '회피',            min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',            min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',       min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 1,   max: 3,    dp: 2 },
                        { name: '공격력(%)',       min: 0.65, max: 0.9,  dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',          min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',        min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',        min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',        min: 35,  max: 150,  dp: 0 },
                        { name: '회피',            min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',            min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',       min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 1,   max: 3,    dp: 2 },
                        { name: '공격력(%)',       min: 0.65, max: 0.9,  dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 150,  dp: 0 },
                        { name: '방어력',          min: 50,  max: 300,  dp: 0 },
                        { name: '최대체력',        min: 150, max: 600,  dp: 0 },
                        { name: '디지소울',        min: 150, max: 600,  dp: 0 },
                        { name: '스킬피해',        min: 50,  max: 300,  dp: 0 },
                        { name: '회피',            min: 2,   max: 4,    dp: 0 },
                        { name: '블럭',            min: 2,   max: 4,    dp: 0 },
                        { name: '방어력(%)',       min: 2,   max: 5,    dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 2,   max: 5,    dp: 2 },
                        { name: '크리티컬',        min: 1,   max: 3,    dp: 2 },
                        { name: '적중도',          min: 200, max: 400,  dp: 2 },
                        { name: '공격력(%)',       min: 0.5,  max: 1.3,  dp: 2 },
                    ],
                    [
                        { name: '공격력',          min: 25,  max: 300,  dp: 0 },
                        { name: '방어력',          min: 50,  max: 600,  dp: 0 },
                        { name: '최대체력',        min: 150, max: 1200, dp: 0 },
                        { name: '디지소울',        min: 150, max: 1200, dp: 0 },
                        { name: '스킬피해',        min: 50,  max: 600,  dp: 0 },
                        { name: '회피',            min: 2,   max: 8,    dp: 0 },
                        { name: '블럭',            min: 2,   max: 8,    dp: 0 },
                        { name: '방어력(%)',       min: 2,   max: 10,   dp: 2 },
                        { name: '최대 DS 증가(%)',  min: 2,   max: 10,   dp: 2 },
                        { name: '크리티컬',        min: 2,   max: 5,    dp: 2 },
                        { name: '적중도',          min: 250, max: 600,  dp: 2 },
                        { name: '공격력(%)',       min: 0.15, max: 1.85, dp: 2 },
                    ],
                ],
            },
        ],
    },

    glasses: {
        group: 'equip',
        lines: 4,
        lockCost: { 0: 1, 1: 2, 2: 5 },
        items: [
            {
                name: '스피릿의 장신구',
                linePools: [
                    [
                        { name: '공격력',            min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',            min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',          min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',          min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',          min: 35,  max: 150,  dp: 0 },
                        { name: '회피',              min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',              min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',         min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 1,   max: 3,    dp: 2 },
                        { name: '최종 데미지 증가(%)', min: 0.65, max: 0.9, dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',            min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',          min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',          min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',          min: 35,  max: 150,  dp: 0 },
                        { name: '회피',              min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',              min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',         min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 1,   max: 3,    dp: 2 },
                        { name: '최종 데미지 증가(%)', min: 0.65, max: 0.9, dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 150,  dp: 0 },
                        { name: '방어력',            min: 50,  max: 300,  dp: 0 },
                        { name: '최대체력',          min: 150, max: 600,  dp: 0 },
                        { name: '디지소울',          min: 150, max: 600,  dp: 0 },
                        { name: '스킬피해',          min: 50,  max: 300,  dp: 0 },
                        { name: '회피',              min: 2,   max: 4,    dp: 0 },
                        { name: '블럭',              min: 2,   max: 4,    dp: 0 },
                        { name: '방어력(%)',         min: 2,   max: 5,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 2,   max: 5,    dp: 2 },
                        { name: '크리티컬',          min: 1,   max: 3,    dp: 2 },
                        { name: '적중도',            min: 200, max: 400,  dp: 2 },
                        { name: '최종 데미지 증가(%)', min: 0.5,  max: 1.3, dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 300,  dp: 0 },
                        { name: '방어력',            min: 50,  max: 600,  dp: 0 },
                        { name: '최대체력',          min: 150, max: 1200, dp: 0 },
                        { name: '디지소울',          min: 150, max: 1200, dp: 0 },
                        { name: '스킬피해',          min: 50,  max: 600,  dp: 0 },
                        { name: '회피',              min: 2,   max: 8,    dp: 0 },
                        { name: '블럭',              min: 2,   max: 8,    dp: 0 },
                        { name: '방어력(%)',         min: 2,   max: 10,   dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 2,   max: 10,   dp: 2 },
                        { name: '크리티컬',          min: 2,   max: 5,    dp: 2 },
                        { name: '적중도',            min: 250, max: 600,  dp: 2 },
                        { name: '최종 데미지 증가(%)', min: 0.15, max: 1.85, dp: 2 },
                    ],
                ],
            },
        ],
    },

    bottom: {
        group: 'equip',
        lines: 4,
        lockCost: { 0: 1, 1: 2, 2: 5 },
        items: [
            {
                name: '스피릿의 하의',
                linePools: [
                    [
                        { name: '공격력',            min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',            min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',          min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',          min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',          min: 35,  max: 150,  dp: 0 },
                        { name: '회피',              min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',              min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',         min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 1,   max: 3,    dp: 2 },
                        { name: '스킬 데미지 증가(%)', min: 1.3, max: 1.85, dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',            min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',          min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',          min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',          min: 35,  max: 150,  dp: 0 },
                        { name: '회피',              min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',              min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',         min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 1,   max: 3,    dp: 2 },
                        { name: '스킬 데미지 증가(%)', min: 1.3, max: 1.85, dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 150,  dp: 0 },
                        { name: '방어력',            min: 50,  max: 300,  dp: 0 },
                        { name: '최대체력',          min: 150, max: 600,  dp: 0 },
                        { name: '디지소울',          min: 150, max: 600,  dp: 0 },
                        { name: '스킬피해',          min: 50,  max: 300,  dp: 0 },
                        { name: '회피',              min: 2,   max: 4,    dp: 0 },
                        { name: '블럭',              min: 2,   max: 4,    dp: 0 },
                        { name: '방어력(%)',         min: 2,   max: 5,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 2,   max: 5,    dp: 2 },
                        { name: '크리티컬',          min: 1,   max: 3,    dp: 2 },
                        { name: '적중도',            min: 200, max: 400,  dp: 2 },
                        { name: '스킬 데미지 증가(%)', min: 1,   max: 2.6, dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 300,  dp: 0 },
                        { name: '방어력',            min: 50,  max: 600,  dp: 0 },
                        { name: '최대체력',          min: 150, max: 1200, dp: 0 },
                        { name: '디지소울',          min: 150, max: 1200, dp: 0 },
                        { name: '스킬피해',          min: 50,  max: 600,  dp: 0 },
                        { name: '회피',              min: 2,   max: 8,    dp: 0 },
                        { name: '블럭',              min: 2,   max: 8,    dp: 0 },
                        { name: '방어력(%)',         min: 2,   max: 10,   dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 2,   max: 10,   dp: 2 },
                        { name: '크리티컬',          min: 2,   max: 5,    dp: 2 },
                        { name: '적중도',            min: 250, max: 600,  dp: 2 },
                        { name: '스킬 데미지 증가(%)', min: 0.4, max: 3.7, dp: 2 },
                    ],
                ],
            },
        ],
    },

    gloves: {
        group: 'equip',
        lines: 4,
        lockCost: { 0: 1, 1: 2, 2: 5 },
        items: [
            {
                name: '스피릿의 장갑',
                linePools: [
                    [
                        { name: '공격력',            min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',            min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',          min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',          min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',          min: 35,  max: 150,  dp: 0 },
                        { name: '회피',              min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',              min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',         min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 1,   max: 3,    dp: 2 },
                        { name: '기본 속성 데미지(%)', min: 1,   max: 2,   dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 100,  dp: 0 },
                        { name: '방어력',            min: 35,  max: 150,  dp: 0 },
                        { name: '최대체력',          min: 100, max: 300,  dp: 0 },
                        { name: '디지소울',          min: 100, max: 300,  dp: 0 },
                        { name: '스킬피해',          min: 35,  max: 150,  dp: 0 },
                        { name: '회피',              min: 1,   max: 2,    dp: 0 },
                        { name: '블럭',              min: 1,   max: 2,    dp: 0 },
                        { name: '방어력(%)',         min: 1,   max: 3,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 1,   max: 3,    dp: 2 },
                        { name: '기본 속성 데미지(%)', min: 1,   max: 2,   dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 150,  dp: 0 },
                        { name: '방어력',            min: 50,  max: 300,  dp: 0 },
                        { name: '최대체력',          min: 150, max: 600,  dp: 0 },
                        { name: '디지소울',          min: 150, max: 600,  dp: 0 },
                        { name: '스킬피해',          min: 50,  max: 300,  dp: 0 },
                        { name: '회피',              min: 2,   max: 4,    dp: 0 },
                        { name: '블럭',              min: 2,   max: 4,    dp: 0 },
                        { name: '방어력(%)',         min: 2,   max: 5,    dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 2,   max: 5,    dp: 2 },
                        { name: '크리티컬',          min: 1,   max: 3,    dp: 2 },
                        { name: '적중도',            min: 200, max: 400,  dp: 2 },
                        { name: '기본 속성 데미지(%)', min: 1,   max: 3,   dp: 2 },
                    ],
                    [
                        { name: '공격력',            min: 25,  max: 300,  dp: 0 },
                        { name: '방어력',            min: 50,  max: 600,  dp: 0 },
                        { name: '최대체력',          min: 150, max: 1200, dp: 0 },
                        { name: '디지소울',          min: 150, max: 1200, dp: 0 },
                        { name: '스킬피해',          min: 50,  max: 600,  dp: 0 },
                        { name: '회피',              min: 2,   max: 8,    dp: 0 },
                        { name: '블럭',              min: 2,   max: 8,    dp: 0 },
                        { name: '방어력(%)',         min: 2,   max: 10,   dp: 2 },
                        { name: '최대 DS 증가(%)',    min: 2,   max: 10,   dp: 2 },
                        { name: '크리티컬',          min: 2,   max: 5,    dp: 2 },
                        { name: '적중도',            min: 250, max: 600,  dp: 2 },
                        { name: '기본 속성 데미지(%)', min: 1,   max: 5,   dp: 2 },
                    ],
                ],
            },
        ],
    },
};
