// Auto-generated from _raw_draws.txt by _parse_draws.py
// Each item: { probability, name, grade } — order intentional.

export const draws = [
    {
        name: "슬픔과 결의 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.1, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "대자연의 힘", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "어웨이 킹 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "대자연의 힘", grade: "U" },
            { probability: 0.1, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "정화의 의식 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.1, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "대자연의 힘", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "궁극홍련기사 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.1, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "대자연의 힘", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "네버랜드의 주인 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.1, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "대자연의 힘", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "자연의 수호자 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.1, name: "대자연의 힘", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "시간 패러독스 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "대자연의 힘", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.1, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "스플렌더 블레이드 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "대자연의 힘", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.1, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "궁극전인 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "대자연의 힘", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "스플렌더 블레이드", grade: "U" },
            { probability: 0.1, name: "알파 인포스", grade: "U" },
        ],
    },
    {
        name: "매혹의 제볼루션 드로우",
        pullCount: 6,
        items: [
            { probability: 0.12, name: "유혹의 이끌림", grade: "U" },
            { probability: 0.02, name: "마이너스 데이터", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "7개의 대죄의 관", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.07, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.07, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.07, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.07, name: "저항의 의지 : 엑자몬", grade: "SSS+" },
            { probability: 0.07, name: "저항의 데이터 : 엑자몬", grade: "SSS+" },
            { probability: 0.08, name: "저항의 데이터 : 리리스몬", grade: "SSS" },
            { probability: 0.08, name: "저항의 데이터 : 발바몬", grade: "SSS" },
            { probability: 0.08, name: "저항의 데이터 : 알파몬 왕룡검-알파", grade: "SSS" },
            { probability: 0.08, name: "저항의 데이터 : 알파몬 왕룡검-베타", grade: "SSS" },
            { probability: 0.08, name: "저항의 데이터 : 제스몬", grade: "SSS" },
            { probability: 0.08, name: "저항의 데이터 : 크레니엄몬", grade: "SSS" },
            { probability: 0.08, name: "저항의 데이터 : 마왕몬", grade: "SSS" },
            { probability: 0.08, name: "저항의 데이터 : 간쿠몬", grade: "SSS" },
            { probability: 0.3, name: "저항의 데이터 : 듀크몬", grade: "SS+" },
            { probability: 0.3, name: "저항의 데이터 : 두프트몬", grade: "SS+" },
            { probability: 0.3, name: "저항의 데이터 : 듀나스몬", grade: "SS+" },
            { probability: 0.25, name: "저항의 데이터 : 알포스브이드라몬", grade: "SS+" },
            { probability: 0.25, name: "저항의 데이터 : 켄타우로스몬", grade: "SS+" },
            { probability: 0.25, name: "저항의 데이터 : 베르제브몬", grade: "SS+" },
            { probability: 0.25, name: "저항의 데이터 : 로드나이트몬", grade: "SS+" },
            { probability: 0.3, name: "저항의 데이터 : 메디벌듀크몬", grade: "SS+" },
            { probability: 0.3, name: "저항의 데이터 : 메기드라몬", grade: "SS+" },
            { probability: 0.25, name: "저항의 데이터 : 카오스드라몬", grade: "SS+" },
            { probability: 0.35, name: "저항의 데이터 : 매그너몬", grade: "SS" },
            { probability: 0.35, name: "저항의 데이터 : 미네르바몬", grade: "SS" },
            { probability: 0.55, name: "저항의 데이터 : 데크스몬", grade: "SS" },
            { probability: 1.26, name: "저항의 데이터 : 알파몬", grade: "S+" },
            { probability: 1.26, name: "저항의 데이터 : 로제몬", grade: "S+" },
            { probability: 1.26, name: "저항의 데이터 : 가이오몬", grade: "S+" },
            { probability: 1.26, name: "저항의 데이터 : 기가시드라몬", grade: "S+" },
            { probability: 1.22, name: "저항의 데이터 : 워그레이몬", grade: "S" },
            { probability: 1.22, name: "저항의 데이터 : 메탈가루몬", grade: "S" },
            { probability: 1.26, name: "저항의 데이터 : 돌고라몬", grade: "S" },
            { probability: 1.26, name: "저항의 데이터 : 데크스돌고라몬", grade: "S" },
            { probability: 2.75, name: "저항의 데이터 : 오류우몬", grade: "A+" },
            { probability: 2.75, name: "저항의 데이터 : 그란드라큐몬", grade: "A+" },
            { probability: 2.75, name: "저항의 데이터 : 다이노타이거몬", grade: "A+" },
            { probability: 2.75, name: "저항의 데이터 : 타이거베스퍼몬", grade: "A+" },
            { probability: 2.75, name: "저항의 데이터 : 그랑디스쿠가몬", grade: "A+" },
            { probability: 2.75, name: "저항의 데이터 : 메탈그레이몬", grade: "A" },
            { probability: 2.75, name: "저항의 데이터 : 워가루몬", grade: "A" },
            { probability: 2.75, name: "저항의 데이터 : 메가로그라우몬", grade: "A" },
            { probability: 2.75, name: "저항의 데이터 : 릴리몬", grade: "A" },
            { probability: 2.31, name: "저항의 데이터 : 아구몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 파피몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 돌몬[라프타드라몬계열]", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 류우다몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 아기벌몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 드라큐몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 길몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 팔몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 그레이몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 가루몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 라프타드라몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 돌가몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 데크스돌가몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 깅류우몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 상굴몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 말벌몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 그라우몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 니드몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 그레이드몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 돌몬[돌가몬계열]", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 돌그레몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 돌몬[데크스돌가몬계열]", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 데크스돌그레몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 히사류우몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 마타돌몬", grade: "N" },
            { probability: 2.31, name: "저항의 데이터 : 캐논벌몬", grade: "N" },
        ],
    },
    {
        name: "7개의 대죄 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "찬란한 문장 : 希", grade: "U" },
            { probability: 0.02, name: "성스러운 문장 : 光", grade: "U" },
            { probability: 0.1, name: "7개의 대죄의 관", grade: "U" },
        ],
    },
    {
        name: "황금의 투신룡 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "7개의 대죄의 관", grade: "U" },
            { probability: 0.02, name: "성스러운 문장 : 光", grade: "U" },
            { probability: 0.1, name: "찬란한 문장 : 希", grade: "U" },
        ],
    },
    {
        name: "종극 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "라스트 에볼루션", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "7개의 대죄의 관", grade: "U" },
            { probability: 0.1, name: "마이너스 데이터", grade: "U" },
        ],
    },
    {
        name: "라스트 에볼루션 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "메타모포시스", grade: "U" },
            { probability: 0.02, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 0.02, name: "마이너스 데이터", grade: "U" },
            { probability: 0.02, name: "시간 파괴자", grade: "U" },
            { probability: 0.02, name: "7개의 대죄의 관", grade: "U" },
            { probability: 0.1, name: "라스트 에볼루션", grade: "U" },
        ],
    },
    {
        name: "성마의 정점 디지털 드로우",
        pullCount: 6,
        items: [
            { probability: 11.24, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 11.24, name: "실비아", grade: "SS+" },
            { probability: 11.24, name: "홀리링", grade: "SS+" },
            { probability: 11.24, name: "펜리르", grade: "SS+" },
            { probability: 11.23, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 11.23, name: "블록조각", grade: "SS+" },
            { probability: 11.23, name: "능천사의 힘 - A", grade: "SS+" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.82, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.82, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.81, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.82, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.82, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.05, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.05, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.05, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.06, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.05, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.05, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.05, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.05, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.05, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.05, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.05, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.05, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.05, name: "그레이트 크로스 - 알파", grade: "SSS+" },
            { probability: 0.02, name: "정화의 의식", grade: "U" },
            { probability: 0.02, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 0.02, name: "알파 인포스", grade: "U" },
            { probability: 0.1, name: "유혹의 이끌림", grade: "U" },
            { probability: 0.1, name: "은백의 성기사", grade: "U" },
        ],
    },
];
