// Auto-generated from _raw_fusion.txt by _parse_fusion.py
// Each fusion group consumes inputCount items of inputGrade → 1 result from `results` (weighted random).
// Groups with `pity`: every Nth attempt also yields 1 additional item from pity.results.

export const fusions = [
    {
        name: "SS 등급 합성",
        inputGrade: "SS",
        inputCount: 4,
        results: [
            { probability: 12.86, name: "신의 의지", grade: "SS" },
            { probability: 12.86, name: "자이언트 미사일", grade: "SS" },
            { probability: 12.86, name: "기사도 정신", grade: "SS" },
            { probability: 12.86, name: "석장", grade: "SS" },
            { probability: 12.86, name: "전설의 진화 - Ω", grade: "SS" },
            { probability: 12.85, name: "궁그닐", grade: "SS" },
            { probability: 12.85, name: "게헤나", grade: "SS" },
            { probability: 1.43, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 1.43, name: "실비아", grade: "SS+" },
            { probability: 1.43, name: "홀리링", grade: "SS+" },
            { probability: 1.43, name: "펜리르", grade: "SS+" },
            { probability: 1.43, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 1.43, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 1.42, name: "블록조각", grade: "SS+" },
        ],
    },
    {
        name: "SS+ 등급 합성",
        inputGrade: "SS+",
        inputCount: 4,
        results: [
            { probability: 12.86, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 12.86, name: "실비아", grade: "SS+" },
            { probability: 12.86, name: "홀리링", grade: "SS+" },
            { probability: 12.86, name: "펜리르", grade: "SS+" },
            { probability: 12.86, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 12.85, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 12.85, name: "블록조각", grade: "SS+" },
            { probability: 0.91, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.91, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.91, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.91, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.91, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.91, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.91, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.91, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.91, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.91, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.9, name: "부서진 자명종 시계", grade: "SSS" },
        ],
    },
    {
        name: "SSS 등급 합성",
        inputGrade: "SSS",
        inputCount: 4,
        results: [
            { probability: 8.19, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 8.19, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 8.18, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 8.18, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 8.18, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 8.18, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 8.18, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 8.18, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 8.18, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 8.18, name: "어둠의 판결", grade: "SSS" },
            { probability: 8.18, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.55, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.57, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.57, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.55, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.55, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.55, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.56, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.57, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.57, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.55, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.55, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.56, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.55, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.55, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.55, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.55, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.55, name: "라스트 에볼루션 : 용기", grade: "SSS+" },
            { probability: 0.55, name: "라스트 에볼루션 : 우정", grade: "SSS+" },
        ],
        pity: {
            every: 5,
            results: [
                { probability: 5.26, name: "Cross Data - 시간 [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "파괴를 관리하는 자 [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "재생을 관리하는 자 [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "그레이트 크로스 - 알파", grade: "SSS+" },
                { probability: 5.27, name: "그레이트 크로스 - 베타 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "XrosUp - 베렌헤나 SDX [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "XrosUp - 메듀리아 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "사악한 데이터의 디지타마 [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "인페리움 비셔스(B) [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "인페리움 비셔스(D) [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "저항의 데이터 : 오메가몬-알파[지급용]", grade: "SSS+" },
                { probability: 5.26, name: "저항의 데이터 : 오메가몬-베타[지급용]", grade: "SSS+" },
                { probability: 5.26, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타[지급용]", grade: "SSS+" },
                { probability: 5.26, name: "임페리얼 클로 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "포지트론 레이저 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "빛나는 용기의 날개 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "희망찬 우정의 날개 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "라스트 에볼루션 : 용기 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "라스트 에볼루션 : 우정 [지급용]", grade: "SSS+" },
            ],
        },
    },
    {
        name: "SSS+ 등급 합성",
        inputGrade: "SSS+",
        inputCount: 4,
        results: [
            { probability: 5.0, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 5.1, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 5.1, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 5.0, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 5.0, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 5.0, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 5.0, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 5.1, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 5.1, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 4.95, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 4.95, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 5.0, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 4.95, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 4.95, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 4.95, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 4.95, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 4.95, name: "라스트 에볼루션 : 용기", grade: "SSS+" },
            { probability: 4.95, name: "라스트 에볼루션 : 우정", grade: "SSS+" },
            { probability: 2.0, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 2.0, name: "정화의 의식", grade: "U" },
            { probability: 2.0, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 2.0, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 2.0, name: "메타모포시스", grade: "U" },
        ],
        pity: {
            every: 10,
            results: [
                { probability: 20.0, name: "슬픔과 결의의 상자 [지급용]", grade: "U" },
                { probability: 20.0, name: "정화의 의식 [지급용]", grade: "U" },
                { probability: 20.0, name: "코드 크라운 : 파이널 크로스 [지급용]", grade: "U" },
                { probability: 20.0, name: "초융합 : 하이브리드 [지급용]", grade: "U" },
                { probability: 20.0, name: "메타모포시스 [지급용]", grade: "U" },
            ],
        },
    },
];
