// Auto-generated from _raw_fusion.txt by _parse_fusion.py
// Each fusion group consumes inputCount items of inputGrade → 1 result from `results` (weighted random).
// Groups with `pity`: every Nth attempt also yields 1 additional item from pity.results.

export const fusions = [
    {
        name: "A 등급 합성",
        inputGrade: "A",
        inputCount: 4,
        results: [
            { probability: 2.65, name: "체스의 신이여, 용서하소서!", grade: "A" },
            { probability: 2.65, name: "뜨거운 정의", grade: "A" },
            { probability: 2.65, name: "깊은 숲의 악마", grade: "A" },
            { probability: 2.65, name: "도망치지만 승리!", grade: "A" },
            { probability: 2.65, name: "바다의 왕", grade: "A" },
            { probability: 2.65, name: "기가 드릴", grade: "A" },
            { probability: 2.65, name: "커넬", grade: "A" },
            { probability: 2.65, name: "슈퍼소닉", grade: "A" },
            { probability: 2.65, name: "공격은 최선의 방어", grade: "A" },
            { probability: 2.65, name: "킹 오브 디지몬", grade: "A" },
            { probability: 2.65, name: "트럼프 소드", grade: "A" },
            { probability: 2.65, name: "천사의반지", grade: "A" },
            { probability: 2.65, name: "D-브리가드", grade: "A" },
            { probability: 2.65, name: "황금 갑옷", grade: "A" },
            { probability: 2.65, name: "왕송곳니", grade: "A" },
            { probability: 2.65, name: "라이프 포스", grade: "A" },
            { probability: 2.65, name: "블랙 레퀴엠", grade: "A" },
            { probability: 2.65, name: "킹스 바이트", grade: "A" },
            { probability: 2.65, name: "스마일리 보머", grade: "A" },
            { probability: 2.65, name: "우드 크로스", grade: "A" },
            { probability: 2.65, name: "재판관", grade: "A" },
            { probability: 2.65, name: "궁극의 곤충", grade: "A" },
            { probability: 2.65, name: "토마호크", grade: "A" },
            { probability: 2.65, name: "쌍사의 지팡이", grade: "A" },
            { probability: 2.64, name: "풀꽃의 여왕", grade: "A" },
            { probability: 2.64, name: "뜨거운 정의", grade: "A" },
            { probability: 2.64, name: "메탈 헤드", grade: "A" },
            { probability: 2.64, name: "마이크", grade: "A" },
            { probability: 2.64, name: "얼티메이트 스피커", grade: "A" },
            { probability: 2.64, name: "드릴 블레이더", grade: "A" },
            { probability: 2.64, name: "행 온 데스", grade: "A" },
            { probability: 2.64, name: "스카 내일", grade: "A" },
            { probability: 2.64, name: "위시 어폰 어 스타", grade: "A" },
            { probability: 2.64, name: "시나오리아", grade: "A" },
            { probability: 0.91, name: "궁극의 고대룡", grade: "A+" },
            { probability: 0.91, name: "가크란", grade: "A+" },
            { probability: 0.91, name: "전설의 용전사", grade: "A+" },
            { probability: 0.91, name: "브레이브 실드", grade: "A+" },
            { probability: 0.91, name: "무한 캐논", grade: "A+" },
            { probability: 0.91, name: "클라우드 미니언", grade: "A+" },
            { probability: 0.91, name: "레이저 사이트", grade: "A+" },
            { probability: 0.91, name: "칠흑의 용전사", grade: "A+" },
            { probability: 0.91, name: "트라이덴트 테일", grade: "A+" },
            { probability: 0.91, name: "호른 스트라이크", grade: "A+" },
            { probability: 0.9, name: "패러사이트", grade: "A+" },
        ],
    },
    {
        name: "A+ 등급 합성",
        inputGrade: "A+",
        inputCount: 4,
        results: [
            { probability: 8.19, name: "궁극의 고대룡", grade: "A+" },
            { probability: 8.19, name: "가크란", grade: "A+" },
            { probability: 8.18, name: "전설의 용전사", grade: "A+" },
            { probability: 8.18, name: "브레이브 실드", grade: "A+" },
            { probability: 8.18, name: "무한 캐논", grade: "A+" },
            { probability: 8.18, name: "클라우드 미니언", grade: "A+" },
            { probability: 8.18, name: "레이저 사이트", grade: "A+" },
            { probability: 8.18, name: "칠흑의 용전사", grade: "A+" },
            { probability: 8.18, name: "트라이덴트 테일", grade: "A+" },
            { probability: 8.18, name: "호른 스트라이크", grade: "A+" },
            { probability: 8.18, name: "패러사이트", grade: "A+" },
            { probability: 0.46, name: "파일 벙커", grade: "S" },
            { probability: 0.46, name: "고고한 존재", grade: "S" },
            { probability: 0.46, name: "레드디지조이드", grade: "S" },
            { probability: 0.46, name: "오션 러브", grade: "S" },
            { probability: 0.46, name: "블루디지조이드", grade: "S" },
            { probability: 0.46, name: "악마 짐승", grade: "S" },
            { probability: 0.46, name: "마왕몬의 목걸이", grade: "S" },
            { probability: 0.46, name: "암흑의 여신", grade: "S" },
            { probability: 0.46, name: "선과 악", grade: "S" },
            { probability: 0.46, name: "영원한 잠", grade: "S" },
            { probability: 0.45, name: "밤의 칼날", grade: "S" },
            { probability: 0.45, name: "성스러운 창", grade: "S" },
            { probability: 0.45, name: "트로이목마", grade: "S" },
            { probability: 0.45, name: "쉐도우윙", grade: "S" },
            { probability: 0.45, name: "트라이 너클", grade: "S" },
            { probability: 0.45, name: "하이퍼캐논", grade: "S" },
            { probability: 0.45, name: "성수룡", grade: "S" },
            { probability: 0.45, name: "코드 크라운", grade: "S" },
            { probability: 0.45, name: "동쪽의 수호자", grade: "S" },
            { probability: 0.45, name: "남쪽의 수호자", grade: "S" },
            { probability: 0.45, name: "서쪽의 수호자", grade: "S" },
            { probability: 0.45, name: "북쪽의 수호자", grade: "S" },
        ],
    },
    {
        name: "S 등급 합성",
        inputGrade: "S",
        inputCount: 4,
        results: [
            { probability: 4.1, name: "파일 벙커", grade: "S" },
            { probability: 4.1, name: "고고한 존재", grade: "S" },
            { probability: 4.09, name: "레드디지조이드", grade: "S" },
            { probability: 4.09, name: "오션 러브", grade: "S" },
            { probability: 4.09, name: "블루디지조이드", grade: "S" },
            { probability: 4.09, name: "악마 짐승", grade: "S" },
            { probability: 4.09, name: "마왕몬의 목걸이", grade: "S" },
            { probability: 4.09, name: "암흑의 여신", grade: "S" },
            { probability: 4.09, name: "선과 악", grade: "S" },
            { probability: 4.09, name: "영원한 잠", grade: "S" },
            { probability: 4.09, name: "밤의 칼날", grade: "S" },
            { probability: 4.09, name: "성스러운 창", grade: "S" },
            { probability: 4.09, name: "트로이목마", grade: "S" },
            { probability: 4.09, name: "쉐도우윙", grade: "S" },
            { probability: 4.09, name: "트라이 너클", grade: "S" },
            { probability: 4.09, name: "하이퍼캐논", grade: "S" },
            { probability: 4.09, name: "성수룡", grade: "S" },
            { probability: 4.09, name: "코드 크라운", grade: "S" },
            { probability: 4.09, name: "동쪽의 수호자", grade: "S" },
            { probability: 4.09, name: "남쪽의 수호자", grade: "S" },
            { probability: 4.09, name: "서쪽의 수호자", grade: "S" },
            { probability: 4.09, name: "북쪽의 수호자", grade: "S" },
            { probability: 0.84, name: "이지스", grade: "S+" },
            { probability: 0.84, name: "여신의 성장", grade: "S+" },
            { probability: 0.84, name: "클라우솔라스", grade: "S+" },
            { probability: 0.84, name: "장난감 총", grade: "S+" },
            { probability: 0.83, name: "디지털 해저드", grade: "S+" },
            { probability: 0.83, name: "오메가 블레이드", grade: "S+" },
            { probability: 0.83, name: "소돔과 고모라", grade: "S+" },
            { probability: 0.83, name: "자명종 시계", grade: "S+" },
            { probability: 0.83, name: "어둠의 근원", grade: "S+" },
            { probability: 0.83, name: "무의 회귀", grade: "S+" },
            { probability: 0.83, name: "트윈 스피어", grade: "S+" },
            { probability: 0.83, name: "저항의 데이터 : 가이오몬", grade: "S+" },
        ],
    },
    {
        name: "S+ 등급 합성",
        inputGrade: "S+",
        inputCount: 4,
        results: [
            { probability: 7.5, name: "이지스", grade: "S+" },
            { probability: 7.5, name: "여신의 성장", grade: "S+" },
            { probability: 7.5, name: "클라우솔라스", grade: "S+" },
            { probability: 7.5, name: "장난감 총", grade: "S+" },
            { probability: 7.5, name: "디지털 해저드", grade: "S+" },
            { probability: 7.5, name: "오메가 블레이드", grade: "S+" },
            { probability: 7.5, name: "소돔과 고모라", grade: "S+" },
            { probability: 7.5, name: "자명종 시계", grade: "S+" },
            { probability: 7.5, name: "어둠의 근원", grade: "S+" },
            { probability: 7.5, name: "무의 회귀", grade: "S+" },
            { probability: 7.5, name: "트윈 스피어", grade: "S+" },
            { probability: 7.5, name: "저항의 데이터 : 가이오몬", grade: "S+" },
            { probability: 1.43, name: "신의 의지", grade: "SS" },
            { probability: 1.43, name: "자이언트 미사일", grade: "SS" },
            { probability: 1.43, name: "기사도 정신", grade: "SS" },
            { probability: 1.43, name: "석장", grade: "SS" },
            { probability: 1.43, name: "전설의 진화 - Ω", grade: "SS" },
            { probability: 1.43, name: "궁그닐", grade: "SS" },
            { probability: 1.42, name: "게헤나", grade: "SS" },
        ],
    },
    {
        name: "SS 등급 합성",
        inputGrade: "SS",
        inputCount: 4,
        results: [
            { probability: 12.86, name: "신의 의지", grade: "SS" },
            { probability: 12.86, name: "자이언트 미사일", grade: "SS" },
            { probability: 12.86, name: "기사도 정신", grade: "SS" },
            { probability: 12.86, name: "석장", grade: "SS" },
            { probability: 12.86, name: "전설의 진화 - Ω", grade: "SS" },
            { probability: 12.85, name: "궁그닐", grade: "SS" },
            { probability: 12.85, name: "게헤나", grade: "SS" },
            { probability: 1.43, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 1.43, name: "실비아", grade: "SS+" },
            { probability: 1.43, name: "홀리링", grade: "SS+" },
            { probability: 1.43, name: "펜리르", grade: "SS+" },
            { probability: 1.43, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 1.43, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 1.42, name: "블록조각", grade: "SS+" },
        ],
    },
    {
        name: "SS+ 등급 합성",
        inputGrade: "SS+",
        inputCount: 4,
        results: [
            { probability: 12.86, name: "바그라몬의 이상과 신념", grade: "SS+" },
            { probability: 12.86, name: "실비아", grade: "SS+" },
            { probability: 12.86, name: "홀리링", grade: "SS+" },
            { probability: 12.86, name: "펜리르", grade: "SS+" },
            { probability: 12.86, name: "라플레시몬 : Data Core - 로제몬", grade: "SS+" },
            { probability: 12.85, name: "능천사의 힘 - B", grade: "SS+" },
            { probability: 12.85, name: "블록조각", grade: "SS+" },
            { probability: 0.91, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 0.91, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 0.91, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 0.91, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 0.91, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 0.91, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 0.91, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 0.91, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 0.91, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 0.91, name: "어둠의 판결", grade: "SSS" },
            { probability: 0.9, name: "부서진 자명종 시계", grade: "SSS" },
        ],
    },
    {
        name: "SSS 등급 합성",
        inputGrade: "SSS",
        inputCount: 4,
        results: [
            { probability: 8.19, name: "매트릭스 에볼루션 - 듀크몬", grade: "SSS" },
            { probability: 8.19, name: "매트릭스 에볼루션 - 세인트가르고몬", grade: "SSS" },
            { probability: 8.18, name: "매트릭스 에볼루션 - 샤크라몬", grade: "SSS" },
            { probability: 8.18, name: "각성한 음의 기운 : 현무몬", grade: "SSS" },
            { probability: 8.18, name: "각성한 음의 기운 : 주작몬", grade: "SSS" },
            { probability: 8.18, name: "각성한 음의 기운 : 백호몬", grade: "SSS" },
            { probability: 8.18, name: "각성한 음의 기운 : 청룡몬", grade: "SSS" },
            { probability: 8.18, name: "더블 크로스 - DX - 알파", grade: "SSS" },
            { probability: 8.18, name: "더블 크로스 - DX - 베타", grade: "SSS" },
            { probability: 8.18, name: "어둠의 판결", grade: "SSS" },
            { probability: 8.18, name: "부서진 자명종 시계", grade: "SSS" },
            { probability: 0.55, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 0.57, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 0.57, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 0.55, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 0.55, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 0.55, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 0.56, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 0.57, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 0.57, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 0.55, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 0.55, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 0.56, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 0.55, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 0.55, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 0.55, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 0.55, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 0.55, name: "라스트 에볼루션 : 용기", grade: "SSS+" },
            { probability: 0.55, name: "라스트 에볼루션 : 우정", grade: "SSS+" },
        ],
        pity: {
            every: 5,
            results: [
                { probability: 5.26, name: "Cross Data - 시간 [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "파괴를 관리하는 자 [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "재생을 관리하는 자 [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "그레이트 크로스 - 알파", grade: "SSS+" },
                { probability: 5.27, name: "그레이트 크로스 - 베타 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "XrosUp - 베렌헤나 SDX [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "XrosUp - 메듀리아 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "사악한 데이터의 디지타마 [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "인페리움 비셔스(B) [지급용]", grade: "SSS+" },
                { probability: 5.27, name: "인페리움 비셔스(D) [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "저항의 데이터 : 오메가몬-알파[지급용]", grade: "SSS+" },
                { probability: 5.26, name: "저항의 데이터 : 오메가몬-베타[지급용]", grade: "SSS+" },
                { probability: 5.26, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타[지급용]", grade: "SSS+" },
                { probability: 5.26, name: "임페리얼 클로 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "포지트론 레이저 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "빛나는 용기의 날개 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "희망찬 우정의 날개 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "라스트 에볼루션 : 용기 [지급용]", grade: "SSS+" },
                { probability: 5.26, name: "라스트 에볼루션 : 우정 [지급용]", grade: "SSS+" },
            ],
        },
    },
    {
        name: "SSS+ 등급 합성",
        inputGrade: "SSS+",
        inputCount: 4,
        results: [
            { probability: 5.0, name: "Cross Data - 시간", grade: "SSS+" },
            { probability: 5.1, name: "파괴를 관리하는 자", grade: "SSS+" },
            { probability: 5.1, name: "재생을 관리하는 자", grade: "SSS+" },
            { probability: 5.0, name: "그레이트 크로스 - 베타", grade: "SSS+" },
            { probability: 5.0, name: "XrosUp - 베렌헤나 SDX", grade: "SSS+" },
            { probability: 5.0, name: "XrosUp - 메듀리아", grade: "SSS+" },
            { probability: 5.0, name: "사악한 데이터의 디지타마", grade: "SSS+" },
            { probability: 5.1, name: "인페리움 비셔스(B)", grade: "SSS+" },
            { probability: 5.1, name: "인페리움 비셔스(D)", grade: "SSS+" },
            { probability: 4.95, name: "저항의 데이터 : 오메가몬-알파", grade: "SSS+" },
            { probability: 4.95, name: "저항의 데이터 : 오메가몬-베타", grade: "SSS+" },
            { probability: 5.0, name: "저항의 데이터 : 알파몬 왕룡검(각성)-베타", grade: "SSS+" },
            { probability: 4.95, name: "임페리얼 클로", grade: "SSS+" },
            { probability: 4.95, name: "포지트론 레이저", grade: "SSS+" },
            { probability: 4.95, name: "빛나는 용기의 날개", grade: "SSS+" },
            { probability: 4.95, name: "희망찬 우정의 날개", grade: "SSS+" },
            { probability: 4.95, name: "라스트 에볼루션 : 용기", grade: "SSS+" },
            { probability: 4.95, name: "라스트 에볼루션 : 우정", grade: "SSS+" },
            { probability: 2.0, name: "슬픔과 결의의 상자", grade: "U" },
            { probability: 2.0, name: "정화의 의식", grade: "U" },
            { probability: 2.0, name: "코드 크라운 : 파이널 크로스", grade: "U" },
            { probability: 2.0, name: "초융합 : 하이브리드", grade: "U" },
            { probability: 2.0, name: "메타모포시스", grade: "U" },
        ],
        pity: {
            every: 10,
            results: [
                { probability: 20.0, name: "슬픔과 결의의 상자 [지급용]", grade: "U" },
                { probability: 20.0, name: "정화의 의식 [지급용]", grade: "U" },
                { probability: 20.0, name: "코드 크라운 : 파이널 크로스 [지급용]", grade: "U" },
                { probability: 20.0, name: "초융합 : 하이브리드 [지급용]", grade: "U" },
                { probability: 20.0, name: "메타모포시스 [지급용]", grade: "U" },
            ],
        },
    },
];
